### ISSUE TITLE
希望能够在改修所需消耗的装备后面显示该消耗品的持有数量

### ISSUE THREAD

**Issue by Sunev** [poooi/plugin-item-improvement#31]
![qq 20180530221958](https://user-images.githubusercontent.com/12387091/40726406-3fd68fcc-6458-11e8-9d91-42f7059b2a6d.png)
大概上面这个样子，这样对我这种记忆力衰退的老年提督会更友好一些

**Comment by KochiyaOcean** [comment]
@Sunev 很早就有计划，但是咕咕
